theme: jekyll-theme-cayman
title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
url: "http://okok7028.github.io"
author:
  name: "Gu M. G."
  email: "a02kiu@gmail.com"
  url: "http://okok7028.github.io"
  
  
  baseurl:
  markdown: kramdown
  source: .
  destination: ./_site
  permalink: /:title
  paginate: 8
  paginate_path: /page:num/
  
  
  defaults:
    -
      scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
